import { useState } from "react";
import { Link } from "react-router-dom";
import { FaRegHeart, FaRegBookmark, FaShare } from "react-icons/fa";
import StaffPicks from "../components/StaffPicks";
import Header from "../components/Header";

const BlogList = ({ searchQuery }) => {
  const blogs = [ 
    { id: "s1", title: "Web Development: Building the Internet, One Page at a Time", content: "From personal blogs to e-commerce stores, websites power the digital world. Our Avanteia Certified Web Development Beginner course teaches HTML, CSS, and JavaScript basics. Get hands-on experience in creating responsive web pages and gain the skills to kickstart your web development journey.From personal blogs to e-commerce stores, websites power the digital world, making web development an essential skill in today's digital era. Our Avanteia Certified Web Development Beginner Course is designed to provide you with a strong foundation in web development by covering the core technologies—HTML, CSS, and JavaScript—that form the backbone of modern websites. Through hands-on experience, you will learn to create responsive and visually appealing web pages, ensuring they adapt seamlessly to different screen sizes and devices. Whether you’re an aspiring developer looking to build your first website or someone eager to explore the world of coding, this course will equip you with the fundamental skills necessary to bring your ideas to life. By the end of the course, you’ll have a solid grasp of essential coding concepts, enabling you to craft interactive and user-friendly web pages while laying the groundwork for more advanced web development practices.", imageUrl: "https://miro.medium.com/v2/resize:fit:640/format:webp/0*S89P7cl_JTUKtoE9.jpg" },
    { id: "s2", title: " Cybersecurity: The First Step Towards a Secure Digital World", content: "In today's digital era, cybersecurity is a must-have skill. Our Avanteia Certified Cybersecurity Beginner course introduces fundamental security concepts, network security, and cyber threats. Students gain hands-on experience in recognizing vulnerabilities and implementing security measures. Whether you’re an aspiring cybersecurity professional or just want to safeguard your digital assets, this course provides a solid foundation.In today's digital era, where cyber threats are constantly evolving, cybersecurity has become a must-have skill for individuals and businesses alike to protect sensitive information and digital assets from potential attacks. Our Avanteia Certified Cybersecurity Beginner Course is designed to introduce you to fundamental security concepts, covering essential topics such as network security, cyber threats, encryption, and risk management, helping you develop a strong understanding of how to identify, analyze, and mitigate security risks effectively. Through hands-on experience, you will learn to recognize vulnerabilities in systems, detect potential cyber threats, and implement proactive security measures to safeguard data and prevent breaches. Whether you’re an aspiring cybersecurity professional aiming to build a career in this ever-growing field or someone looking to enhance personal and professional cybersecurity awareness, this course provides a comprehensive foundation that equips you with the knowledge and practical skills needed to secure digital environments and stay ahead of cybercriminals in an increasingly interconnected world.", imageUrl: "https://avanteia.com/assets/img/blog/single_blog_2.webp" },
    { id: "s3", title: "Blockchain Development: The Future of Decentralized Technology", content: "Blockchain is revolutionizing industries far beyond cryptocurrencies, transforming sectors such as finance, healthcare, supply chain management, and digital identity by providing enhanced security, transparency, and decentralization. Our Avanteia Certified Blockchain Development Beginner Course is designed to give you a comprehensive introduction to blockchain technology, covering fundamental concepts such as distributed ledgers, consensus mechanisms, smart contracts, and real-world use cases that demonstrate its vast potential. You will learn how blockchain enables secure and tamper-proof transactions, fostering trust in a decentralized environment while eliminating the need for intermediaries. Through hands-on experience, you will explore the process of developing decentralized applications (DApps), deploying smart contracts on blockchain networks, and understanding the role of platforms like Ethereum and Binance Smart Chain in blockchain development. Whether you are an aspiring blockchain developer looking to build innovative solutions or simply want to grasp how blockchain technology enhances security, efficiency, and trust in digital interactions, this course will guide you through the essentials and empower you to navigate the future of decentralized technology with confidence.", imageUrl: "https://miro.medium.com/v2/resize:fit:720/format:webp/1*zNSOODS3UjW5VKPW0EO4lA.png" },
    { id: "s4", title: "Digital Marketing: Mastering Online Growth Strategies", content: "Digital marketing is the backbone of modern businesses, playing a crucial role in enhancing brand visibility, attracting customers, and driving business growth in an increasingly competitive online landscape. Our Avanteia Certified Digital Marketing Beginner Course is designed to equip you with essential skills and knowledge, covering key areas such as Search Engine Optimization (SEO), social media marketing, content creation strategies, pay-per-click (PPC) advertising, email marketing, and data analytics to help you understand how to effectively promote businesses in the digital space. Through hands-on learning, you will explore how to optimize websites for search engines, craft compelling content, leverage social media platforms for audience engagement, and create impactful marketing campaigns that drive conversions and sales. Whether you’re an entrepreneur aiming to grow your business, a freelancer looking to offer digital marketing services, or a marketing enthusiast eager to develop a strong foundation in this ever-evolving field, this course provides you with practical strategies and insights to navigate the digital world with confidence and achieve measurable results. By mastering the fundamentals of digital marketing, you’ll gain the ability to build an online presence, connect with target audiences, and stay ahead in the dynamic world of digital advertising and brand promotion.", imageUrl: "https://miro.medium.com/v2/resize:fit:720/format:webp/1*xBl1sg-oRz6cfE3YKI_HxQ.png" },
    { id: "s5", title: "Internet of Things (IoT): Connecting Devices for a Smarter World", content: "The Internet of Things (IoT) is revolutionizing the way we interact with technology, seamlessly integrating smart devices into our daily lives and industries. As businesses and individuals increasingly rely on connected devices to enhance efficiency and automation, understanding IoT fundamentals has become essential. The Avanteia Certified IoT Beginner course is designed to provide a comprehensive introduction to the world of IoT, covering key concepts such as IoT architecture, sensors, connectivity, and data analysis. This course delves into how smart devices collect and transmit data, enabling intelligent decision-making in real-time. Participants will learn about various types of sensors and their applications, how data is processed and analyzed, and the role of cloud computing and edge computing in IoT ecosystems. Moreover, the course explores real-world applications of IoT across industries, such as healthcare, agriculture, smart homes, and industrial automation, demonstrating how IoT solutions can optimize processes, reduce costs, and improve overall efficiency. By gaining hands-on experience in building basic IoT applications, learners will acquire the foundational knowledge and skills needed to develop innovative IoT solutions. Whether you are a student, a professional looking to upskill, or an entrepreneur aiming to leverage IoT for business growth, this course provides a strong starting point. Embrace the future of connected technology with the Avanteia Certified IoT Beginner course and take the first step toward mastering the exciting world of IoT.", imageUrl: "https://miro.medium.com/v2/resize:fit:640/format:webp/1*QbTUL4ihq2b-CFbWLCzwJg.png" },
    { id: "s6", title: "Artificial Intelligence: Unlocking the Power of Smart Machines", content: "Artificial Intelligence (AI) is at the heart of modern technological advancements, driving innovations that are transforming industries and redefining the way we interact with machines. From personalized recommendations and voice assistants to self-driving cars and advanced data analytics, AI is shaping the future in unprecedented ways. The Avanteia Certified AI Beginner course is designed to introduce learners to the foundational concepts of AI, providing a strong understanding of machine learning, deep learning, and essential AI tools. This course covers the core principles of how machines learn from data, recognize patterns, and make intelligent decisions, enabling automation and enhanced problem-solving capabilities. Participants will explore the different types of machine learning, including supervised, unsupervised, and reinforcement learning, and gain insights into neural networks and deep learning architectures that power advanced AI applications. Additionally, the course delves into real-world AI use cases, such as building chatbots, automating repetitive tasks, and analyzing vast amounts of data for meaningful insights. Learners will also get hands-on experience with AI tools and frameworks that are widely used in the industry, equipping them with practical skills to develop AI-driven solutions. Whether you are a student looking to start a career in AI, a professional aiming to upskill, or an entrepreneur seeking to integrate AI into your business, this course provides the fundamental knowledge needed to navigate the rapidly growing field of artificial intelligence. With the Avanteia Certified AI Beginner course, you can take the first step toward mastering AI and unlocking its vast potential to drive innovation and efficiency in various domains.", imageUrl: "https://media.istockphoto.com/id/1387900612/photo/automation-data-analytic-with-robot-and-digital-visualization-for-big-data-scientist.jpg?s=612x612&w=0&k=20&c=50maOJU6CpVC55mYnUqtff2aiaJZ7KlmMn4jNhWD_eo=" },
    { id: "s7", title: "Machine Learning: Making Computers Think Smarter", content: "Machine learning is revolutionizing industries by enabling data-driven insights, automating complex tasks, and enhancing decision-making processes across various domains. From healthcare and finance to marketing and cybersecurity, machine learning is driving innovation by allowing systems to learn from data and improve performance without being explicitly programmed. The Avanteia Certified Machine Learning Beginner course provides a comprehensive introduction to the fundamental concepts of machine learning, equipping learners with the essential knowledge needed to build intelligent models. This course covers both supervised and unsupervised learning, helping participants understand how algorithms can be trained using labeled data or find patterns in unlabeled data. Additionally, the course delves into feature engineering, a crucial step in preparing data for machine learning models by selecting and transforming relevant variables to improve predictive accuracy. Learners will also explore model evaluation techniques, understanding how to assess the performance of machine learning models using key metrics such as accuracy, precision, recall, and F1-score. Through practical examples and hands-on exercises, participants will gain experience in working with real datasets, training machine learning models, and making data-driven predictions. This course is ideal for students, data enthusiasts, and professionals looking to analyze data, extract meaningful patterns, and develop predictive models that drive business growth and efficiency. Whether you aim to enhance your analytical skills, pursue a career in data science, or leverage machine learning for automation and innovation, the Avanteia Certified Machine Learning Beginner course offers a strong foundation to help you succeed in this rapidly evolving field.", imageUrl: "https://static.vecteezy.com/system/resources/previews/007/136/275/non_2x/machine-learning-modern-computer-technologies-concept-artificial-intelligence-ai-photo.jpg" },
    { id: "s8", title: " Data Science: Extracting Insights from Data", content:"Data is often referred to as the new gold, as it holds immense value for businesses and organizations seeking to gain a competitive edge in today’s digital world. With the rapid growth of data generation across industries, the ability to collect, process, and analyze data effectively has become a crucial skill. The Avanteia Certified Data Science Beginner course is designed to introduce learners to the fundamental concepts of data science, equipping them with the essential knowledge and tools needed to extract meaningful insights from raw data. This course covers the data collection process, teaching participants how to gather, clean, and preprocess data from various sources to ensure its quality and reliability. Additionally, learners will explore data visualization techniques, learning how to represent data graphically using charts, plots, and interactive dashboards to uncover trends, patterns, and correlations that support data-driven decision-making. The course also provides an introduction to basic machine learning models, allowing participants to understand how algorithms can be used to identify patterns and make predictions based on historical data. Through hands-on exercises and real-world examples, learners will gain practical experience in using data science tools and techniques to analyze datasets and generate actionable insights. Whether you are a student looking to start a career in data science, a professional aiming to enhance your analytical skills, or a business owner seeking to leverage data for strategic decision-making, this course provides a solid foundation. The Avanteia Certified Data Science Beginner course empowers you to turn raw data into valuable insights, helping you unlock the potential of data science and drive innovation in various fields.", imageUrl: "https://pg-p.ctme.caltech.edu/wp-content/uploads/sites/4/2023/07/What-is-Data-Science.jpg" },
    { id: "s9", title: "Cloud Computing: Powering the Digital World from the Cloud", content: "Cloud computing has transformed the way businesses store, manage, and process data, providing scalable and cost-effective solutions that enhance efficiency and innovation. With organizations increasingly shifting from traditional on-premises infrastructure to cloud-based environments, understanding cloud computing has become an essential skill. The Avanteia Certified Cloud Computing Beginner course is designed to introduce learners to the fundamental concepts of cloud computing, equipping them with the knowledge and hands-on experience needed to navigate this rapidly growing field. The course covers cloud fundamentals, explaining the core principles of cloud computing, including its service models (IaaS, PaaS, SaaS) and deployment models (public, private, hybrid, and multi-cloud). Participants will gain insights into how cloud computing enables businesses to scale resources on demand, optimize costs, and improve operational flexibility. Additionally, the course explores major cloud platforms, such as Amazon Web Services (AWS), Microsoft Azure, and Google Cloud Platform (GCP), providing an overview of their key features, services, and use cases. Learners will also delve into cloud security, understanding the best practices for securing cloud-based applications, managing access controls, and ensuring data protection in cloud environments. A key highlight of the course is its hands-on approach, where participants get the opportunity to work with cloud services, deploy applications, and manage cloud resources in real-world scenarios. Whether you are a student exploring career opportunities in cloud computing, an IT professional looking to upskill, or a business owner seeking to leverage the cloud for digital transformation, The Avanteia Certified Cloud Computing Beginner course provides a strong foundation to help you succeed. Gain the skills needed to deploy and manage cloud-based applications efficiently and unlock the full potential of cloud technology.", imageUrl: "https://millionwebservices.com/wp-content/uploads/2023/06/cloud-consulting-banner.png" },
    { id: "s10", title: "Solidity: The Language of Smart Contracts", content: "Ethereum and blockchain technology have revolutionized the digital landscape by enabling decentralized applications (DApps) and smart contracts, which operate without intermediaries. At the heart of Ethereum-based development lies Solidity, a high-level programming language specifically designed for writing smart contracts on the Ethereum Virtual Machine (EVM). The Avanteia Certified Solidity Beginner course provides a comprehensive introduction to smart contract development, blockchain fundamentals, and essential security practices, equipping learners with the skills needed to build decentralized solutions. This course begins with an overview of blockchain architecture, explaining the key principles behind distributed ledgers, consensus mechanisms, and decentralized networks. Participants will gain a deep understanding of how Ethereum works, including transaction processing, gas fees, and the role of miners or validators in maintaining the network. A major focus of the course is on Solidity programming, where learners will explore variables, functions, control structures, and object-oriented programming concepts within Solidity. They will also work on hands-on projects, writing, compiling, and deploying smart contracts using development tools such as Remix IDE and Hardhat. Security is a critical aspect of blockchain development, and this course emphasizes smart contract security best practices, covering common vulnerabilities like reentrancy attacks, overflow/underflow issues, and improper access control. By understanding these risks, learners will be able to develop more secure and efficient smart contracts. The course is ideal for aspiring blockchain developers, entrepreneurs, and tech enthusiasts looking to create decentralized applications (DApps) for industries such as finance (DeFi), supply chain, gaming, and digital identity. Whether you are new to blockchain or looking to enhance your skills in Ethereum development, The Avanteia Certified Solidity Beginner course provides a strong foundation to help you confidently build, test, and deploy smart contracts in the decentralized world.", imageUrl: "https://miro.medium.com/v2/resize:fit:1000/0*M8BCHiLneEKYybv-.jpg" },
    { id: "s11", title: "Big Data: Managing Information at Scale", content: "In today’s digital world, businesses generate and collect vast amounts of data every second, making big data a crucial asset for informed decision-making. From customer behavior analysis and financial forecasting to healthcare diagnostics and real-time fraud detection, big data technologies are revolutionizing industries by enabling organizations to process, analyze, and extract valuable insights from massive datasets. The Avanteia Certified Big Data Beginner course is designed to introduce learners to the fundamentals of big data, equipping them with essential knowledge of industry-leading tools and frameworks such as Hadoop and Spark, as well as core data processing techniques. The course begins with an overview of big data architecture, explaining how distributed computing and storage systems handle enormous volumes of structured and unstructured data. Participants will learn how Hadoop functions as a scalable storage and processing framework, utilizing components like HDFS (Hadoop Distributed File System) and MapReduce to manage large-scale datasets across multiple nodes. Additionally, the course delves into Apache Spark, a powerful big data analytics engine that enables real-time and batch processing, making data analysis faster and more efficient. Learners will gain hands-on experience in working with these tools, understanding how to clean, transform, and analyze data for meaningful insights. Moreover, the course covers big data processing techniques, including data ingestion, transformation, and querying, helping learners understand how businesses leverage these techniques to enhance decision-making and optimize operations. Whether you are an aspiring data engineer, analyst, or IT professional, this course provides a strong foundation in big data concepts and applications. By the end of The Avanteia Certified Big Data Beginner course, learners will have the skills to efficiently analyze and manage large datasets, making them valuable assets in the ever-evolving field of data science and analytics.", imageUrl: "https://assets.datamation.com/uploads/2023/09/dm_09152023-big-data-management.png" },
    { id: "s12", title: " Python Programming: The Most Versatile Programming Language", content: "Python is widely used in AI, web development, and automation. The Avanteia Certified Python Programming Beginner course teaches Python syntax, loops, functions, and file handling. Ideal for beginners looking to enter software development.", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEre2CZaLQ8Kf522Dcu6gsDmvkyzpheYB9gfdjXcH7Vr_aUcTffNPJwoB3o2Xu7isV9FE&usqp=CAU" },
    { id: "s13", title: "Programming with Rust, Kotlin, Java, and More", content:"Programming languages are the foundation of software development, each offering unique features and capabilities suited for different applications, from system programming and web development to mobile apps and enterprise solutions. If you’re eager to expand your programming knowledge and enhance your skills, Avanteia offers beginner courses in a variety of popular programming languages, including Rust, Kotlin, Java, C, C++, C#, and Go. These courses are designed to help learners understand the fundamental concepts of each language, including syntax, control flow, functions, data structures, and object-oriented principles, providing a strong foundation for software development.The Rust programming course introduces learners to a powerful and memory-safe language, ideal for system programming, embedded systems, and high-performance applications. For those interested in mobile development, the Kotlin course focuses on building Android applications efficiently with a modern and expressive syntax. Java, one of the most widely used programming languages, is essential for enterprise applications, web development, and Android programming, making it a great choice for aspiring developers. Meanwhile, the C and C++ courses provide a deep dive into low-level programming, teaching memory management, pointers, and performance optimization, which are crucial for game development, operating systems, and embedded systems. The C# course is perfect for those looking to develop applications in the Microsoft ecosystem, including Windows applications, game development with Unity, and enterprise solutions. Lastly, the Go (Golang) course introduces learners to Google’s efficient and scalable language, widely used for cloud computing, networking, and backend development.Each course includes hands-on exercises and real-world examples, ensuring that learners not only understand theoretical concepts but also gain practical experience in writing and debugging code. Whether you’re a beginner exploring your first programming language or an experienced developer looking to expand your expertise, Avanteia’s beginner programming courses will help you build a strong foundation and become a well-rounded developer ready to tackle various software development challenges.", imageUrl: "https://media2.dev.to/dynamic/image/width=1280,height=720,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fwww.rust-lang.org%2Fstatic%2Fimages%2Frust-social-wide.jpg" },
    { id: "s14", title: " SQL: The Language of Databases", content: "Databases serve as the backbone of modern applications, enabling businesses and developers to store, manage, and retrieve data efficiently. Whether it’s an e-commerce website, financial system, healthcare application, or social media platform, databases play a critical role in handling vast amounts of structured information. The Avanteia Certified SQL Beginner course is designed to introduce learners to the fundamentals of Structured Query Language (SQL) and relational database management, equipping them with essential skills to organize and manipulate data effectively. This course begins with an overview of database concepts, explaining the importance of relational databases and how they are used to store and manage data in an organized manner. Participants will learn how to work with SQL, the standard language for interacting with databases, mastering key commands for creating, reading, updating, and deleting (CRUD) data.The course covers writing queries to retrieve specific data, filtering records using conditions, sorting and grouping data, and using joins to combine information from multiple tables. Additionally, learners will explore data manipulation techniques, such as inserting, updating, and deleting records, ensuring database integrity and efficiency. Understanding indexes, primary keys, foreign keys, and normalization will help participants design optimized database structures that enhance performance and prevent redundancy. Security and data integrity are also emphasized, introducing best practices for user access control, data validation, and transaction management. Through hands-on exercises and real-world projects, learners will gain practical experience in working with relational databases like MySQL, PostgreSQL, and SQLite, enabling them to apply their knowledge to real-world applications.Whether you are an aspiring data analyst, software developer, or IT professional, this course provides a strong foundation in SQL and database management, preparing you for roles that involve handling and analyzing data efficiently. By the end of The Avanteia Certified SQL Beginner course, learners will have the confidence to design, query, and manage relational databases, making them valuable assets in today’s data-driven world.", imageUrl: "https://media.istockphoto.com/id/1800292591/photo/sql-structured-query-language-technology-concept-icon-virtual-screen.jpg?s=612x612&w=0&k=20&c=Natt2t_aFsr-KlPiMMQUPKIX6sbDb2hOTRhUFcSq6cA=" },
  ];

  const filteredBlogs = blogs.filter(blog =>
    blog.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
    blog.content.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="px-4 sm:px-8 lg:px-24 pt-4 mx-auto flex flex-col lg:flex-row gap-6 sm:gap-12">
      <div className="w-full lg:w-2/3">
        {filteredBlogs.length > 0 ? (
          filteredBlogs.map((blog) => (
            <Link to={`/blog/${blog.id}`} key={blog.id} className="block">
              <article className="bg-white p-4 sm:p-6 rounded-lg shadow-md flex flex-col sm:flex-row items-start gap-2 sm:gap-6 mb-4 hover:shadow-lg transition-shadow">
                <img
                  src={blog.imageUrl}
                  alt={blog.title}
                  className="w-full sm:w-40 h-auto sm:h-32 object-cover rounded-md max-w-full"
                />
                <div className="flex-1">
                  <h2 className="text-base sm:text-xl font-bold text-gray-900 mt-1">
                    {blog.title}
                  </h2>
                  <p className="text-gray-700 mt-2 text-sm sm:text-base">
                    {blog.content.substring(0, 150)}...
                  </p>
                  <Link
                    to={`/blog/${blog.id}`}
                    className="text-blue-500 hover:underline mt-2 block text-sm sm:text-base"
                  >
                    Read More
                  </Link>
                  <div className="flex items-center gap-2 sm:gap-4 mt-3 text-gray-600">
                    <FaRegHeart className="hover:text-red-500 cursor-pointer text-sm sm:text-base" />
                    <FaRegBookmark className="hover:text-blue-500 cursor-pointer text-sm sm:text-base" />
                    <FaShare className="hover:text-green-500 cursor-pointer text-sm sm:text-base" />
                  </div>
                </div>
              </article>
            </Link>
          ))
        ) : (
          <p className="text-center text-gray-500">No blogs found</p>
        )}
      </div>
      <div className="w-full lg:w-1/3">
        <StaffPicks />
      </div>
    </div>
  );
};

const CoursePage = () => {
  const [searchQuery, setSearchQuery] = useState("");

  return (
    <div>
      <Header onSearch={setSearchQuery} />
      <BlogList searchQuery={searchQuery} />
    </div>
  );
};

export default CoursePage;

  